spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smartcity_unla
    username: root
    password: homer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false